apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-storage
  namespace: vault
  labels:
    app: vault
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
