apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    ui = true
    
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = true
    }
    
    storage "file" {
      path = "/vault/data"
    }
    
    # Enable Kubernetes auth method
    auth "kubernetes" {
      type = "kubernetes"
    }
    
    # API address for clustering
    api_addr = "http://vault.vault.svc.cluster.local:8200"
    cluster_addr = "http://vault.vault.svc.cluster.local:8201"
    
    # Disable mlock for GKE Autopilot compatibility
    # Autopilot security constraints don't allow IPC_LOCK capability
    # In production on standard GKE, enable mlock for better security
    disable_mlock = true
